services:
  parameter_server:
    build: .
    container_name: parameter_server
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: python main.py --role parameter_server --id 0 --host 0.0.0.0 --port 5000
    stdin_open: true
    tty: true
    shm_size: '2gb'

  